server:
  port: 8300

jwt:
  secret:
    key: abcdefget!@#$$ADFASDF1239408390dsfvjnjasfhasdkfjnvfvjfvASDFASDFSDFOV@#2349
spring:
  application:
    name: gateway-service
  redis:
    host: localhost
    port: 6379
    password: password1234
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8100
          predicates:
            - Path=/user-service/login, /user-service/users
            - Method=POST
        - id: user-service
          uri: http://localhost:8100
          filters:
            - JwtAuthenticationFilter
          predicates:
            - Path=/user-service/**
        - id: community-service
          uri: http://localhost:8200
          predicates:
            - Path=/community-service/**
          filters:
            - JwtAuthenticationFilter
management:
  endpoints:
    web:
      exposure:
        include:
          - "gateway"
  endpoint:
    gateway:
      enabled: true
