server:
  port: 8100
jwt:
  secret:
    key: abcdefget!@#$$ADFASDF1239408390dsfvjnjasfhasdkfjnvfvjfvASDFASDFSDFOV@#2349
spring:
  application:
    name: user-service
  redis:
    host: localhost
    port: 6379
    password: password1234
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver